import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  Dimensions,
} from 'react-native';
import { Exercise } from '../types/database';

interface WorkoutSummaryImageProps {
  userName: string;
  workoutDate: string;
  workoutTitle: string;
  completedExercises: (Exercise & { sets?: number; reps?: string })[];
}

const WorkoutSummaryImage: React.FC<WorkoutSummaryImageProps> = ({
  userName,
  workoutDate,
  workoutTitle,
  completedExercises,
}) => {
  const { width } = Dimensions.get('window');
  const imageWidth = Math.min(width - 40, 400);
  
  return (
    <View style={[styles.container, { width: imageWidth }]}>
      {/* 헤더 */}
      <View style={styles.header}>
        <Text style={styles.title}>운동 완료! 🎉</Text>
        <Text style={styles.userName}>{userName}님</Text>
        <Text style={styles.date}>{workoutDate}</Text>
      </View>

      {/* 운동 제목 */}
      <View style={styles.workoutTitleContainer}>
        <Text style={styles.workoutTitle}>{workoutTitle}</Text>
      </View>

      {/* 완료된 운동 목록 */}
      <View style={styles.exercisesContainer}>
        <Text style={styles.exercisesHeader}>완료한 운동</Text>
        {completedExercises.map((exercise, index) => (
          <View key={exercise.id} style={styles.exerciseItem}>
            <View style={styles.exerciseNumber}>
              <Text style={styles.exerciseNumberText}>{index + 1}</Text>
            </View>
            <View style={styles.exerciseDetails}>
              <Text style={styles.exerciseName}>{exercise.name}</Text>
              {exercise.sets && exercise.reps && (
                <Text style={styles.exerciseInfo}>
                  {exercise.sets}세트 × {exercise.reps}회
                </Text>
              )}
            </View>
            <View style={styles.checkmarkContainer}>
              <Text style={styles.checkmark}>✓</Text>
            </View>
          </View>
        ))}
      </View>

      {/* 격려 메시지 */}
      <View style={styles.encouragementContainer}>
        <Text style={styles.encouragementText}>
          훌륭한 운동이었어요!
        </Text>
        <Text style={styles.encouragementSubtext}>
          꾸준히 운동하여 목표를 달성해보세요! 💪
        </Text>
      </View>

      {/* 워터마크 */}
      <View style={styles.watermark}>
        <Text style={styles.watermarkText}>Generated by GymMate</Text>
        <Text style={styles.watermarkLogo}>🏋️‍♂️</Text>
      </View>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 24,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 8,
  },
  header: {
    alignItems: 'center',
    marginBottom: 20,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#1C1C1E',
    marginBottom: 8,
    textAlign: 'center',
  },
  userName: {
    fontSize: 20,
    fontWeight: '600',
    color: '#007AFF',
    marginBottom: 4,
  },
  date: {
    fontSize: 16,
    color: '#8E8E93',
    fontWeight: '500',
  },
  workoutTitleContainer: {
    backgroundColor: '#F2F2F7',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginBottom: 20,
    width: '100%',
  },
  workoutTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1C1C1E',
    textAlign: 'center',
  },
  exercisesContainer: {
    width: '100%',
    marginBottom: 20,
  },
  exercisesHeader: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1C1C1E',
    marginBottom: 12,
    textAlign: 'center',
  },
  exerciseItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: '#F8F9FA',
    borderRadius: 8,
    marginBottom: 6,
  },
  exerciseNumber: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#007AFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  exerciseNumberText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: 'bold',
  },
  exerciseDetails: {
    flex: 1,
  },
  exerciseName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1C1C1E',
    marginBottom: 2,
  },
  exerciseInfo: {
    fontSize: 14,
    color: '#007AFF',
    fontWeight: '500',
  },
  checkmarkContainer: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#34C759',
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkmark: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: 'bold',
  },
  encouragementContainer: {
    alignItems: 'center',
    marginBottom: 16,
  },
  encouragementText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#34C759',
    marginBottom: 4,
    textAlign: 'center',
  },
  encouragementSubtext: {
    fontSize: 14,
    color: '#8E8E93',
    textAlign: 'center',
    lineHeight: 20,
  },
  watermark: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#E5E5EA',
    width: '100%',
    justifyContent: 'center',
  },
  watermarkText: {
    fontSize: 12,
    color: '#8E8E93',
    fontWeight: '500',
    marginRight: 4,
  },
  watermarkLogo: {
    fontSize: 14,
  },
});

export default WorkoutSummaryImage;
